### PR TITLE
Correct some grammar errors in the README.

### PR DESCRIPTION
**Pull request by shlomif**
Hi! Thanks for Emscripten. This pull-req correct some grammatical errors in the README. Please consider merging it.

### CODE REVIEW

**Comment by shlomif** [comment]
Hi all , and happy Easter and Purim!

Why wasn't this pull-req merged yet? Is there anything I can do?

**Comment by juj** [comment]
Oops, sorry, this had just fallen through my view in email. Thanks!

**Comment by shlomif** [comment]
Thanks for merging!

**Comment by shlomif** [comment]
Also see https://gist.github.com/xdg/7dd1713dda777e95567e for a GitHub dashboard.

**Pull request merged**
