### PR TITLE
Fix powershell env directory

### PR DESCRIPTION
**Pull request by saschanaz**
It should use `./` to access the current directory.

(I added emsdk to the system path so I couldn't catch this. Sorry 😅)

### CODE REVIEW

**Comment by jakobmulvad** [comment]
Was just about to open the same pull request. This was my fix as well.

**Comment by DTasev** [comment]
@juj Can confirm this works with the current master, `./emsdk_env.ps1` can now properly set the environment. Please merge this in or remove the PowerShell scripts as of right now the only thing they do is get you halfway there and give an error.

**Comment by saschanaz** [comment]
Sorry to bother you twice, but would be happy if you review this 😆 @juj

**Comment by kripken** [comment]
@juj, if you're too busy to review&merge stuff in a timely manner in this repo, perhaps someone else should be given merge powers?

**Comment by juj** [comment]
Sorry for the delay, this had fallen through my attention!

@kripken : that's a good observation, even if this was my full time attention, we should still have more admins on this repo. I'll make you an administrator on this as well to get started on getting more collaborators.

**Pull request merged**
